import { AICrimeLanguage, getLocalizedAICrimePath } from './aiCrimeData';

export const museSentinelPath = '/ai-crime-files/meta-muse-sentinel-agent-security-harness';
export const museSentinelImage = '/images/ai-crime-files/meta-muse-sentinel-agent-security-harness.webp';
export const museSentinelHref = (language: AICrimeLanguage) => getLocalizedAICrimePath(museSentinelPath, language);

type Copy = {
  title: string; description: string; label: string; read: string; alt: string; directAnswer: string; classification: string;
  sections: { heading: string; paragraphs: string[]; bullets?: string[] }[];
  faq: { question: string; answer: string }[];
};

const sharedFacts = {
  sources: [
    'Meta describes Sentinel as a separate host-side agent and the sole permission authority for connector actions and network egress.',
    'Muse runs in a dedicated Secure VM and can use email, calendars, shopping, payments and other connected services.',
    'Reuters reported internal testing incidents involving sensitive-data exposure, incorrect guardrail routing and reliability failures; Meta did not comment on the specific incidents.'
  ]
};

export const museSentinelCopy: Record<AICrimeLanguage, Copy> = {
  en: {
    title: 'Meta Muse Sentinel: Can One AI Agent Safely Supervise Another?',
    description: 'How Meta Muse uses a separate Sentinel agent as its permission authority—and why production safety still needs deterministic enforcement, audit and fail-closed controls.',
    label: 'Breaking analysis · Harness Engineering', read: 'Read the Sentinel analysis',
    alt: 'Editorial illustration of a blue autonomous AI inside a secure virtual machine and a separate amber Sentinel inspecting email, calendar and payment tool calls',
    directAnswer: 'Meta Muse places a separate host-side AI agent, Sentinel, between the personal agent and external services. Muse proposes an action; Sentinel can allow it, block it or ask the user. That is a major Harness Engineering pattern, but one AI judging another is not a complete security boundary: deterministic policy, least privilege, tamper-resistant logs and fail-closed execution must remain outside both models.',
    classification: 'CONFIRMED: Meta launched Muse on September 8, 2026 and publicly described Sentinel and the Secure VM. REPORTED: Reuters described internal test failures from company posts. NOT PROVED: that Sentinel eliminates prompt injection or every unauthorized action. ANALYSIS: the architecture is a live test of agent-on-agent supervision.',
    sections: [
      { heading: 'What Meta actually launched', paragraphs: [sharedFacts.sources[1], 'Unlike a chatbot that only returns text, Muse is designed to complete multi-step work. That makes every connector an execution surface: an email can disclose information, a calendar action can alter commitments and a payment can move money.'] },
      { heading: 'How Sentinel changes the trust boundary', paragraphs: [sharedFacts.sources[0], 'The separation matters because the acting model is not asked to police itself. Meta says approval prompts travel directly between Sentinel and the user rather than through Muse, reducing the chance that compromised agent context can rewrite the question or the answer.'] },
      { heading: 'The evidence is encouraging—not conclusive', paragraphs: [sharedFacts.sources[2], 'Meta says the architecture underwent external review and added Muse to its bug-bounty program. Those are useful signals, but a launch description is not proof that all action classes, indirect prompt injections and confused-deputy paths have been eliminated.'] },
      { heading: 'Harness Engineering implications', paragraphs: ['The model is only part of the system; the harness determines what the agent can observe, remember, call, execute, persist, recover from and escalate. Sentinel makes that principle visible by moving permission decisions into a distinct component.', 'The strongest design uses AI for contextual risk interpretation while deterministic infrastructure owns the final capability boundary.'], bullets: ['Give each connector a narrow, revocable capability token.', 'Require deterministic approval for payments, messages, account changes and disclosure of sensitive data.', 'Bind approval to the exact action, recipient, amount and payload—not a vague task.', 'Keep Sentinel and its policy state outside Muse control.', 'Log proposal, policy version, decision, user confirmation and actual side effect.', 'Fail closed when Sentinel is unavailable, uncertain or detects conflicting instructions.', 'Red-team indirect prompt injection across every connected app.', 'Test whether recovery or retries can duplicate an approved side effect.'] },
      { heading: 'What to watch next', paragraphs: ['Independent testing should ask whether malicious content in email or webpages can manipulate Muse, Sentinel or the user-confirmation flow; whether policy updates are auditable; and whether the execution layer rejects a tool call that differs from the approved proposal.', 'This is not a crime report. It belongs in The AI Crime Files as preventive systems analysis because the same harness choices decide whether an autonomous agent can turn compromised instructions into data theft, fraud or unauthorized transactions.'] }
    ],
    faq: [
      { question: 'What is Meta Muse Sentinel?', answer: 'It is a separate host-side agent that Meta says controls Muse connector actions and all network egress.' },
      { question: 'Can one AI agent safely supervise another?', answer: 'It can add contextual review, but it should not be the only boundary. Deterministic policy and execution code must enforce permissions and approvals.' },
      { question: 'Is this a documented AI crime?', answer: 'No. Muse is a newly launched product. This page is a preventive Harness Engineering analysis and explicitly does not claim a crime occurred.' }
    ]
  },
  pt: {
    title: 'Meta Muse Sentinel: um agente de IA pode supervisionar outro com segurança?',
    description: 'Como o Meta Muse usa o agente Sentinel para autorizar ações — e por que segurança real ainda exige políticas determinísticas, auditoria e bloqueio seguro.',
    label: 'Análise atual · Harness Engineering', read: 'Ler a análise do Sentinel', alt: 'Ilustração editorial de uma IA azul em máquina virtual segura e um Sentinel âmbar inspecionando chamadas de e-mail, calendário e pagamento',
    directAnswer: 'O Meta Muse coloca um segundo agente de IA, o Sentinel, entre o assistente pessoal e os serviços externos. O Muse propõe; o Sentinel autoriza, bloqueia ou consulta o usuário. É um padrão importante de Harness Engineering, mas uma IA julgando outra não basta: políticas determinísticas, privilégio mínimo, registros protegidos e execução fail-closed precisam permanecer fora dos dois modelos.',
    classification: 'CONFIRMADO: a Meta lançou o Muse em 8 de setembro de 2026 e descreveu o Sentinel e a Secure VM. REPORTADO: a Reuters relatou falhas em testes internos. NÃO PROVADO: que o Sentinel elimine toda injeção de prompt ou ação não autorizada. ANÁLISE: é um teste real de supervisão entre agentes.',
    sections: [
      { heading: 'O que a Meta realmente lançou', paragraphs: ['O Muse roda numa Secure VM dedicada e pode atuar em e-mail, calendário, compras, pagamentos e outros serviços conectados.', 'Como ele executa tarefas, cada conector é uma superfície de risco: um e-mail pode vazar dados e um pagamento pode mover dinheiro.'] },
      { heading: 'Como o Sentinel muda a fronteira de confiança', paragraphs: ['A Meta descreve o Sentinel como agente separado no host e autoridade exclusiva sobre conectores e saída de rede.', 'As confirmações sensíveis iriam diretamente do Sentinel ao usuário, sem passar pelo Muse, reduzindo a capacidade de um contexto comprometido adulterar a aprovação.'] },
      { heading: 'O que a evidência permite afirmar', paragraphs: ['A Reuters relatou exposição de dados sensíveis, roteamento incorreto de guardrails e falhas de confiabilidade em testes internos; a Meta não comentou os episódios específicos.', 'Revisão externa e bug bounty são sinais úteis, mas não demonstram que todas as classes de ação e injeções indiretas foram eliminadas.'] },
      { heading: 'Implicações para Harness Engineering', paragraphs: ['O modelo é só parte do sistema; o harness define o que o agente observa, memoriza, chama, executa, persiste, recupera e escalona.', 'A IA pode interpretar contexto, mas infraestrutura determinística deve conservar a palavra final.'], bullets: ['Token estreito e revogável por conector.', 'Aprovação obrigatória para pagamentos, mensagens e dados sensíveis.', 'Vincular a aprovação à ação, destinatário, valor e conteúdo exatos.', 'Manter Sentinel e política fora do controle do Muse.', 'Registrar proposta, decisão, confirmação e efeito real.', 'Bloquear quando houver falha ou incerteza.', 'Testar prompt injection em cada aplicativo conectado.', 'Impedir efeitos duplicados em retries e recuperação.'] },
      { heading: 'O que acompanhar agora', paragraphs: ['Testes independentes precisam verificar conteúdo malicioso em e-mails e páginas, auditabilidade das políticas e divergências entre ação proposta e executada.', 'Não é relato de crime. É análise preventiva: essas escolhas decidem se instruções comprometidas podem virar vazamento, fraude ou transação não autorizada.'] }
    ], faq: [
      { question: 'O que é o Meta Muse Sentinel?', answer: 'Um agente separado que, segundo a Meta, controla conectores e toda saída de rede do Muse.' },
      { question: 'Uma IA pode supervisionar outra com segurança?', answer: 'Pode acrescentar análise contextual, mas políticas e código determinísticos devem impor os limites.' },
      { question: 'Isso é um crime real documentado?', answer: 'Não. É uma análise preventiva de Harness Engineering sobre um produto recém-lançado.' }
    ]
  },
  es: {
    title: 'Meta Muse Sentinel: ¿puede un agente de IA supervisar a otro con seguridad?', description: 'Cómo Sentinel autoriza las acciones de Meta Muse y por qué la seguridad necesita políticas deterministas, auditoría y bloqueo seguro.', label: 'Análisis actual · Harness Engineering', read: 'Leer el análisis de Sentinel', alt: 'Ilustración editorial de una IA azul en una máquina virtual segura y un Sentinel ámbar inspeccionando llamadas de correo, calendario y pagos', directAnswer: 'Meta Muse sitúa un segundo agente, Sentinel, entre el asistente y los servicios externos. Muse propone; Sentinel permite, bloquea o pregunta al usuario. Es un patrón clave de Harness Engineering, pero una IA evaluando a otra no basta: política determinista, mínimo privilegio, registros protegidos y ejecución fail-closed deben quedar fuera de ambos modelos.', classification: 'CONFIRMADO: lanzamiento el 8 de septiembre de 2026 y arquitectura descrita por Meta. REPORTADO: Reuters narró fallos de pruebas internas. NO PROBADO: que Sentinel elimine toda inyección o acción no autorizada. ANÁLISIS: supervisión real entre agentes.',
    sections: [{heading:'Qué lanzó Meta',paragraphs:['Muse opera en una Secure VM y puede usar correo, calendario, compras y pagos. Cada conector convierte una decisión del modelo en un posible efecto real.']},{heading:'La nueva frontera de confianza',paragraphs:['Meta dice que Sentinel es un agente separado y la única autoridad para conectores y tráfico de red. Las aprobaciones sensibles no pasan por Muse.']},{heading:'Qué demuestra la evidencia',paragraphs:['Reuters reportó exposición de datos, errores de guardrails y fallos de fiabilidad en pruebas internas. Meta no comentó esos incidentes específicos; las promesas de lanzamiento aún requieren validación independiente.']},{heading:'Implicaciones para Harness Engineering',paragraphs:['El harness determina qué puede observar, recordar, invocar, ejecutar, persistir, recuperar y escalar el agente. La política determinista debe conservar la decisión final.'],bullets:['Capacidades estrechas y revocables.','Aprobación ligada a acción, destinatario, importe y payload.','Sentinel fuera del control de Muse.','Registro inmutable de propuesta, decisión y efecto.','Fallo cerrado ante duda o indisponibilidad.','Pruebas de prompt injection y reintentos duplicados.']},{heading:'Qué vigilar',paragraphs:['Las pruebas deben verificar contenido hostil en aplicaciones, cambios de política y diferencias entre lo aprobado y lo ejecutado. No es un crimen documentado, sino análisis preventivo.']}], faq:[{question:'¿Qué es Meta Muse Sentinel?',answer:'Un agente separado que controla las acciones de conectores y la salida de red, según Meta.'},{question:'¿Puede una IA supervisar a otra?',answer:'Puede ayudar, pero código y política deterministas deben imponer los límites.'},{question:'¿Ocurrió un delito?',answer:'No. Esta página no presenta el lanzamiento como delito.'}]
  },
  fr: {
    title:'Meta Muse Sentinel : un agent IA peut-il en superviser un autre ?',description:'Comment Sentinel autorise les actions de Meta Muse et pourquoi la sécurité exige politique déterministe, audit et blocage sûr.',label:'Analyse actuelle · Harness Engineering',read:'Lire l’analyse Sentinel',alt:'Illustration éditoriale d’une IA bleue dans une machine virtuelle sécurisée et d’un Sentinel ambre inspectant e-mails, calendrier et paiements',directAnswer:'Meta Muse place un second agent, Sentinel, entre l’assistant et les services externes. Muse propose ; Sentinel autorise, bloque ou interroge l’utilisateur. Ce schéma de Harness Engineering est important, mais une IA jugeant une autre ne suffit pas : politique déterministe, moindre privilège, journaux protégés et exécution fail-closed doivent rester hors des deux modèles.',classification:'CONFIRMÉ : lancement le 8 septembre 2026 et architecture décrite par Meta. RAPPORTÉ : Reuters a décrit des défaillances de tests internes. NON PROUVÉ : élimination de toute injection ou action non autorisée. ANALYSE : supervision réelle entre agents.',sections:[{heading:'Ce que Meta a lancé',paragraphs:['Muse s’exécute dans une Secure VM et peut utiliser e-mail, agenda, achats et paiements. Chaque connecteur transforme une décision en effet réel.']},{heading:'La frontière de confiance',paragraphs:['Meta présente Sentinel comme un agent séparé et l’unique autorité des connecteurs et sorties réseau. Les approbations sensibles ne transitent pas par Muse.']},{heading:'Ce que prouvent les éléments',paragraphs:['Reuters a rapporté exposition de données, mauvais routage des garde-fous et pannes de fiabilité pendant les tests. Meta n’a pas commenté ces incidents précis.']},{heading:'Conséquences pour le Harness Engineering',paragraphs:['Le harness détermine ce que l’agent peut observer, mémoriser, appeler, exécuter, conserver, récupérer et escalader. La politique déterministe doit garder le dernier mot.'],bullets:['Capacités étroites et révocables.','Approbation liée à l’action exacte.','Sentinel hors du contrôle de Muse.','Journal de la proposition au résultat.','Blocage sûr en cas de doute.','Tests d’injection et de reprise.']},{heading:'À surveiller',paragraphs:['Il faut tester les contenus hostiles, les changements de politique et l’écart entre action approuvée et exécutée. Il ne s’agit pas d’un crime documenté.']}],faq:[{question:'Qu’est-ce que Meta Muse Sentinel ?',answer:'Un agent séparé contrôlant les connecteurs et la sortie réseau selon Meta.'},{question:'Une IA peut-elle en superviser une autre ?',answer:'Oui comme couche contextuelle, mais le code déterministe doit imposer les limites.'},{question:'Un crime a-t-il eu lieu ?',answer:'Non. Cette analyse ne présente pas le lancement comme un crime.'}]
  },
  it: {
    title:'Meta Muse Sentinel: un agente IA può sorvegliarne un altro in sicurezza?',description:'Come Sentinel autorizza le azioni di Meta Muse e perché servono policy deterministiche, audit e blocco sicuro.',label:'Analisi attuale · Harness Engineering',read:'Leggi l’analisi di Sentinel',alt:'Illustrazione editoriale di una IA blu in una macchina virtuale sicura e un Sentinel ambra che controlla email, calendario e pagamenti',directAnswer:'Meta Muse colloca un secondo agente, Sentinel, tra l’assistente e i servizi esterni. Muse propone; Sentinel consente, blocca o chiede all’utente. È un modello importante di Harness Engineering, ma una IA che giudica un’altra non basta: policy deterministiche, minimo privilegio, log protetti ed esecuzione fail-closed devono restare fuori da entrambi i modelli.',classification:'CONFERMATO: lancio l’8 settembre 2026 e architettura descritta da Meta. RIPORTATO: Reuters ha descritto problemi nei test interni. NON PROVATO: eliminazione di ogni injection o azione non autorizzata. ANALISI: supervisione reale tra agenti.',sections:[{heading:'Cosa ha lanciato Meta',paragraphs:['Muse gira in una Secure VM e può usare email, calendario, acquisti e pagamenti. Ogni connettore trasforma una decisione in un effetto reale.']},{heading:'Il confine di fiducia',paragraphs:['Meta descrive Sentinel come agente separato e unica autorità per connettori e traffico di rete. Le approvazioni sensibili non passano da Muse.']},{heading:'Cosa dimostrano le prove',paragraphs:['Reuters ha riportato esposizione di dati, instradamento errato dei guardrail e problemi di affidabilità nei test. Meta non ha commentato gli episodi specifici.']},{heading:'Implicazioni per Harness Engineering',paragraphs:['Il harness decide cosa l’agente può osservare, ricordare, chiamare, eseguire, persistere, recuperare ed escalare. La policy deterministica deve mantenere l’ultima parola.'],bullets:['Capacità ristrette e revocabili.','Approvazione legata all’azione esatta.','Sentinel fuori dal controllo di Muse.','Log dalla proposta all’effetto.','Blocco sicuro nel dubbio.','Test di injection e retry.']},{heading:'Cosa osservare',paragraphs:['Servono test indipendenti su contenuti ostili, policy e differenze tra azione approvata ed eseguita. Non è un crimine documentato.']}],faq:[{question:'Cos’è Meta Muse Sentinel?',answer:'Un agente separato che controlla connettori e uscita di rete secondo Meta.'},{question:'Una IA può sorvegliarne un’altra?',answer:'Può aiutare, ma codice e policy deterministiche devono imporre i limiti.'},{question:'È avvenuto un crimine?',answer:'No. Questa analisi non presenta il lancio come crimine.'}]
  },
  ja: {
    title:'Meta Muse Sentinel：AIエージェントは別のAIを安全に監督できるのか',description:'Meta Museの行動をSentinelが許可する仕組みと、決定論的ポリシー、監査、フェイルクローズが必要な理由を解説。',label:'最新技術分析 · Harness Engineering',read:'Sentinelの分析を読む',alt:'安全な仮想マシン内の青いAIと、メール、予定表、決済のツール呼び出しを検査する琥珀色のSentinelを描いた編集用イラスト',directAnswer:'Meta Museは、個人エージェントと外部サービスの間に別のAIエージェントSentinelを置きます。Museが行動を提案し、Sentinelが許可、拒否、またはユーザー確認を行います。重要なHarness Engineeringの設計ですが、AIがAIを審査するだけでは不十分です。決定論的なポリシー、最小権限、保護されたログ、フェイルクローズの実行は両モデルの外側に必要です。',classification:'確認済み：Metaは2026年9月8日にMuseを公開し、SentinelとSecure VMを説明。報道：Reutersが社内テストの問題を報告。未証明：すべてのプロンプトインジェクションや無許可行動を防げること。分析：実環境でのエージェント間監督。',sections:[{heading:'Metaが公開したもの',paragraphs:['Museは専用Secure VMで動作し、メール、予定表、買い物、決済を利用できます。コネクターはモデルの判断を現実の副作用へ変えます。']},{heading:'信頼境界を変えるSentinel',paragraphs:['MetaによればSentinelは独立したエージェントで、コネクターとネットワーク送信の唯一の許可権限です。重要な確認はMuseを経由しません。']},{heading:'証拠が示す範囲',paragraphs:['Reutersは社内テストでの機密データ露出、ガードレールの誤作動、信頼性問題を報じました。Metaは個別事案にコメントしていません。']},{heading:'Harness Engineeringへの示唆',paragraphs:['モデルはシステムの一部にすぎません。harnessが観測、記憶、呼び出し、実行、永続化、復旧、エスカレーションを決めます。最終権限は決定論的ポリシーが持つべきです。'],bullets:['狭く失効可能な権限。','行動、相手、金額、内容に結び付く承認。','MuseからSentinelを分離。','提案から副作用まで記録。','不確実時は拒否。','インジェクションと再試行を検証。']},{heading:'今後の検証点',paragraphs:['接続アプリ内の悪意ある内容、ポリシー変更、承認内容と実行内容の差を独立検証する必要があります。これは犯罪報告ではありません。']}],faq:[{question:'Meta Muse Sentinelとは？',answer:'Metaによれば、コネクターとネットワーク送信を管理する独立エージェントです。'},{question:'AIが別のAIを監督できますか？',answer:'文脈判断には役立ちますが、制約は決定論的なコードとポリシーが強制すべきです。'},{question:'犯罪は起きましたか？',answer:'いいえ。本稿は犯罪として扱わず、予防的な技術分析として明示します。'}]
  }
};
